<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

$output .= 'div#bbpress-forums .bbp-topic-title .bbp-topic-meta .bbp-topic-started-in > a {background: '.$vars['main_site_color'].';}';

$output .= 'div#bbpress-forums .forums.bbp-replies .bbp-body > div .bbp-reply-content .dfd-bbpress-content-wrap p a {color: '.$vars['main_site_color'].';}';

/* Buttons */
$output .=	 '#bbpress-forums .bbp-reply-content #subscription-toggle .subscription-toggle,'
			.'#bbpress-forums > #subscription-toggle .subscription-toggle,'
			.'#bbpress-forums .bbp-reply-content #favorite-toggle .favorite-toggle {'
				.'font-family: '.$vars['default_button-font-family'].';'
				.'font-size: '.$vars['default_button-font-size'].';'
				.'font-style: '.$vars['default_button-font-style'].';'
				.'font-weight: '.$vars['default_button-font-weight'].';'
				.'text-transform: '.$vars['default_button-text-transform'].';'
				.'letter-spacing: '.$vars['default_button-letter-spacing'].';'
			.'}';

$output .=   '#bbpress-forums .bbp-forum-info .bbp-forum-content,'
			.'#bbpress-forums li.bbp-forum-freshness,'
			.'#bbpress-forums li.bbp-topic-freshness,'
			.'#bbpress-forums div.bbp-template-notice p,'
			.'#bbpress-forums .bbp-pagination-count,'
			.'.bbp-reply-header .bbp-meta .bbp-reply-post-date,'
			.'.bbp-user-section .bbp-reply-header .bbp-meta .bbp-header,'
			.'#bbpress-forums li.bbp-body .bbp-topic-header .bbp-topic-post-date,'
			.'.bbp-reply-header .bbp-meta .bbp-reply-permalink,'
			.'#bbpress-forums #bbp-search-results li.bbp-body .bbp-topic-permalink,'
			.'#bbpress-forums .bbp-topic-started-by,'
			.'#bbpress-forums .bbp-topic-started-in,'
			.'#bbpress-forums div.bbp-the-content-wrapper input,'
			.'#bbpress-forums fieldset.bbp-form legend,'
			.'#bbpress-forums .forums.bbp-replies .bbp-body > div .bbp-reply-author .bbp-author-role,'
			.'#bbpress-forums .forums.bbp-replies .bbp-body > div .bbp-reply-author .bbp-reply-ip,'
			.'div#bbpress-forums .bbp-search-results .bbp-reply-ip,'
			.'div#bbpress-forums .bbp-search-results .bbp-author-role,'
			.'#bbpress-forums .bbp-search-results li.bbp-body > div .bbp-topic-title h3 > a,'
			.'#bbpress-forums .bbp-search-results li.bbp-body > div .bbp-topic-title .bbp-topic-title-meta > a,'
			.'#bbpress-forums .bbp-search-results li.bbp-body > div .bbp-reply-title h3 > a,'
			.'#bbp-user-wrapper .bbp-user-section > p,'
			.'div#bbpress-forums #bbp-user-wrapper #bbp-your-profile fieldset fieldset.password span.description,'
			.'#bbpress-forums blockquote,'
			.'#bbpress-forums .bbp-reply-revision-log li {'
				.'font-family: '.$vars['content_subtitle-font-family'].';'
				.'font-size: '.$vars['content_subtitle-font-size'].';'
				.'font-style: '.$vars['content_subtitle-font-style'].';'
				.'font-weight: '.$vars['content_subtitle-font-weight'].';'
				.'text-transform: '.$vars['content_subtitle-text-transform'].';'
				.'line-height: '.$vars['content_subtitle-line-height'].';'
				.'letter-spacing: '.$vars['content_subtitle-letter-spacing'].';'
				.'color: '.$vars['content_subtitle-color'].';'
			.'}';

$output .=   '#bbpress-forums li.bbp-header .forum-titles,'
			.'#bbpress-forums li.bbp-body .bbp-forum-title,'
			.'#bbpress-forums li.bbp-body .bbp-topic-permalink,'
			.'#bbpress-forums li.bbp-forum-topic-count,'
			.'#bbpress-forums li.bbp-topic-voice-count,'
			.'#bbpress-forums li.bbp-forum-reply-count,'
			.'#bbpress-forums li.bbp-topic-reply-count,'
			.'#bbpress-forums li.bbp-header .bbp-forum-author,'
			.'#bbpress-forums li.bbp-footer .bbp-forum-author,'
			.'#bbpress-forums li.bbp-header .bbp-topic-author,'
			.'#bbpress-forums li.bbp-footer .bbp-topic-author,'
			.'#bbpress-forums li.bbp-header .bbp-reply-author,'
			.'#bbpress-forums li.bbp-footer .bbp-reply-author,'
			.'#bbpress-forums li.bbp-header .bbp-search-content,'
			.'#bbpress-forums li.bbp-header .bbp-search-author,'
			.'#bbpress-forums li.bbp-footer .bbp-search-content,'
			.'#bbpress-forums li.bbp-header .bbp-forum-content,'
			.'#bbpress-forums li.bbp-footer .bbp-forum-content,'
			.'#bbpress-forums li.bbp-header .bbp-topic-content,'
			.'#bbpress-forums li.bbp-footer .bbp-topic-content,'
			.'#bbpress-forums li.bbp-header .bbp-reply-content,'
			.'#bbpress-forums li.bbp-footer .bbp-reply-content,'
			.'#bbpress-forums .bbp-admin-links a,'
			.'#bbpress-forums .bbp-forums-list,'
			.'#bbpress-forums .bbp-topic-pagination .page-numbers,'
			.'#bbpress-forums .bbp-pagination-links .page-numbers,'
			.'#bbpress-forums .bbp-topic-started-in > a,'
			.'#bbpress-forums .forums.bbp-replies .bbp-body > div .bbp-reply-author .bbp-author-name,'
			.'#bbpress-forums .bbp-search-results .bbp-author-name,'
			.'#bbpress-forums .bbp-search-results li.bbp-body > div .bbp-topic-title h3,'
			.'#bbpress-forums .bbp-search-results li.bbp-body > div .bbp-reply-title h3,'
			.'#bbpress-forums .bbp-search-results li.bbp-body > div .bbp-topic-title .bbp-topic-title-meta,'
			.'#bbpress-forums #bbp-user-wrapper h2.entry-title {'
				.'font-family: '.$vars['loop_product_title-font-family'].';'
				.'font-size: '.$vars['loop_product_title-font-size'].';'
				.'font-style: '.$vars['loop_product_title-font-style'].';'
				.'font-weight: '.$vars['loop_product_title-font-weight'].';'
				.'text-transform: '.$vars['loop_product_title-text-transform'].';'
				.'line-height: '.$vars['loop_product_title-line-height'].';'
				.'letter-spacing: '.$vars['loop_product_title-letter-spacing'].';'
				.'color: '.$vars['loop_product_title-color'].';'
			.'}';

$output .=   '#bbpress-forums fieldset.bbp-form label,'
			.'#bbpress-forums div.bbp-topic-tags p {'
				.'font-family: '.$vars['content_title_small-font-family'].';'
				.'font-size: '.$vars['content_title_small-font-size'].';'
				.'font-style: '.$vars['content_title_small-font-style'].';'
				.'font-weight: '.$vars['content_title_small-font-weight'].';'
				.'text-transform: '.$vars['content_title_small-text-transform'].';'
				.'line-height: '.$vars['content_title_small-line-height'].';'
				.'letter-spacing: '.$vars['content_title_small-letter-spacing'].';'
				.'color: '.$vars['content_title_small-color'].';'
			.'}';